steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE}']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        bash ./scripts/cloudrun-deploy.sh "$PROJECT_ID" "${_IMAGE}" "${_SERVICE_NAME}" "${_REGION}" "${_SERVICE_ACCOUNT}"

images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE}'

substitutions:
  _IMAGE: 'rightelect-server:latest'
  _SERVICE_NAME: 'rightelect-server'
  _REGION: 'us-central1'
  _SERVICE_ACCOUNT: 'rightelect-sa@tidy-node-494313-j1.iam.gserviceaccount.com'

timeout: '1200s'
